### ISSUE TITLE
Files are strange - Generate Icons & Splash (Launch) Images

### ISSUE THREAD

**Issue by findvivian** [FokkeZB/TiCons-Server-PHP#24]
Hi Fokke,

Noticed you have updated the Generator again and took a test run. Currently it seems like it just takes the 2208x2208 splash image and sizes it down without cropping. GooglePlay image is also not cropped and sized like they used to be. Is there a quick fix for this?

Is it possible to upload your previous version to another link for use? It works really stable and has all the nice features since being able to customize the ios versus android icon is also a nice feature.

Thank you!

**Comment by FokkeZB** [comment]
The new repo for issues is:
https://github.com/FokkeZB/TiCons-Server

Could you create a ticket there and include the exact config (will be visible after submitting the form) in which case you get these error?
